"""UI- and persistence-independent shared Eolas knowledge kernel."""

from eolas.domain.entities import (
    Authority,
    AuthorityRegistration,
    ContinuityAction,
    Contact,
    ContactRoute,
    GuidanceReference,
    Interaction,
    Organisation,
    OrganisationBrand,
    OrganisationRole,
    PartyRole,
    Person,
)
from eolas.domain.graph import ContinuityDependency, DependencyGraph
from eolas.domain.values import (
    Classification,
    EvidenceReference,
    Fact,
    FactState,
    Identifier,
    Jurisdiction,
    Money,
    Observation,
    Provenance,
    RecordIdentity,
    RecordLifecycle,
    RecordReference,
    ReviewState,
    Schedule,
)

__all__ = [
    "Authority",
    "AuthorityRegistration",
    "Classification",
    "Contact",
    "ContactRoute",
    "ContinuityAction",
    "ContinuityDependency",
    "DependencyGraph",
    "EvidenceReference",
    "Fact",
    "FactState",
    "GuidanceReference",
    "Identifier",
    "Interaction",
    "Jurisdiction",
    "Money",
    "Observation",
    "Organisation",
    "OrganisationBrand",
    "OrganisationRole",
    "PartyRole",
    "Person",
    "Provenance",
    "RecordIdentity",
    "RecordLifecycle",
    "RecordReference",
    "ReviewState",
    "Schedule",
]
